---
swagger: "2.0"
info:
  description: "Contains all available API endpoints in this codebase"
  version: "1.0.6"
  title: "Argent Bank API documentation"
  termsOfService: "http://swagger.io/terms/"
host: "localhost:3001"
basePath: "/api/v2"
tags:
- name: "transactions"
  description: "Operations related to transactions"
schemes:
- "http"
paths:
  /transactions:
    get:
      tags:
      - "transactions"
      summary: "Retrieves a list of all transactions for the last month"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Bearer (apiKey)"
        required: true
        type: "string"
      produces:
      - "application/json"
      responses:
        200:
          description: "List of transactions retrieved successfully"
          schema:
            $ref: "#/definitions/ApiResponse"
        500:
          description: "Internal Server Error"
  /transactions/{transactionId}:
    get:
      tags:
      - "transactions"
      summary: "Fetches details for a specific transaction"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Bearer (apiKey)"
        required: true
        type: "string"
      - name: "transactionId"
        in: "path"
        description: "ID of the transaction"
        required: true
        type: "number"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Transaction"
        404:
          description: "Transaction not found"
        500:
          description: "Internal Server Error"
  /transactions/{transactionId}/note:
    post:
      security:
        - Bearer: []
      tags:
      - "transactions"
      summary: "Adds a note to the details of the specified transaction"
      parameters:
      - name: "transactionId"
        in: "path"
        description: "ID of the transaction"
        required: true
        type: "number"
      responses:
        200:
          description: "Note added successfully"
          schema:
            $ref: "#/definitions/TransactionDetails"
        404:
          description: "Transaction not found"
    put:
      security:
        - Bearer: []
      tags:
      - "transactions"
      summary: "Updates the note in the details of the specified transaction"
      parameters:
      - name: "transactionId"
        in: "path"
        description: "ID of the transaction"
        required: true
        type: "number"
      produces:
      - "application/json"
      responses:
        200:
          description: "Note updated successfully"
          schema:
            $ref: "#/definitions/TransactionDetails"
        400:
          description: "Invalid value"
    delete:
      security:
        - Bearer: []
      tags:
      - "transactions"
      summary: "Removes the note from the details of the specified transaction"
      parameters:
      - name: "transactionId"
        in: "path"
        description: "ID of the transaction"
        required: true
        type: "number"
      responses:
        200:
          description: "Note deleted successfully"
          schema:
            $ref: "#/definitions/TransactionDetails"
        500:
          description: "Internal Server Error"
      deprecated: true
  /transactions/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
      - "transactions"
      summary: "Updates the category in the details of the specified transaction"
      parameters:
      - name: "transactionId"
        in: "path"
        description: "ID of the transaction"
        required: true
        type: "number"
      produces:
      - "application/json"
      responses:
        200:
          description: "Category updated successfully"
          schema:
            $ref: "#/definitions/TransactionDetails"
        400:
          description: "Invalid value"
    
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ApiResponse:
    type: "object"
    properties:
      id:
        type: "number"
      title:
        type: "string"
      amount:
        type: "number"
      description:
        type: "string"
  Transaction:
    type: "object"
    properties:
      id:
        type: "number"
      date:
        type: "string"
        format: "DD/MM/YY"
      description:
        type: "string"
      amount:
        type: "number"
      balance:
        type: "number"
  TransactionDetails:
    type: "object"
    properties:
      id:
        type: "number"
      transactionType:
        type: "string"
      category:
        type: "string"
      note: 
        type: "string"
  
        
  
